services:
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=math_tutor
            - POSTGRES_USER=math_tutor
            - POSTGRES_PASSWORD=math_tutor
        ports:
            - "5432:5432"

volumes:
    postgres_data:
