services:
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=math_tutor
            - POSTGRES_USER=math_tutor
            - POSTGRES_PASSWORD=math_tutor
        ports:
            - "5432:5432"
    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
volumes:
    postgres_data:
    redis_data:
