# Generated by Django 5.1.6 on 2025-02-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("math_content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standrewstopic",
            name="category",
        ),
        migrations.AddField(
            model_name="standrewstopic",
            name="topic_link",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="standrewsbiography",
            name="link",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="standrewstopic",
            name="link",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="standrewstopic",
            name="topic",
            field=models.TextField(),
        ),
    ]
