# Generated by Django 5.1.6 on 2025-02-15 23:20

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("math_content", "0003_remove_standrewsbiography_html_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StAndrewsCurve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.TextField()),
                ("link", models.URLField(unique=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AlterModelOptions(
            name="standrewsbiography",
            options={"ordering": ["year_start", "title"]},
        ),
        migrations.AlterModelOptions(
            name="standrewstopic",
            options={"ordering": ["topic", "title"]},
        ),
        migrations.RemoveField(
            model_name="standrewsbiography",
            name="mathematician",
        ),
        migrations.AddField(
            model_name="standrewsbiography",
            name="year_end",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="standrewsbiography",
            name="year_end_bc",
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="standrewsbiography",
            name="year_start",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="standrewsbiography",
            name="year_start_bc",
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
