# Generated by Django 5.1.6 on 2025-02-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "math_content",
            "0004_standrewscurve_alter_standrewsbiography_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="standrewsbiography",
            options={"ordering": ["title"]},
        ),
    ]
