# Generated by Django 5.1.6 on 2025-02-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("math_content", "0005_alter_standrewsbiography_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="standrewsbiography",
            name="year_order",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
