# Generated by Django 5.1.6 on 2025-02-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("math_content", "0006_standrewsbiography_year_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="standrewsbiography",
            options={"ordering": ["year_order", "title"]},
        ),
        migrations.AddField(
            model_name="collatzconjecture",
            name="total_distance",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collatzconjecture",
            name="two_adic_distance_sequence",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collatzconjecture",
            name="two_adic_total_distance",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
